# Generated by Django 4.0.1 on 2022-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
