# Generated by Django 4.0.1 on 2022-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_rename_password_user_price_rename_name_user_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
