# Generated by Django 4.0.1 on 2022-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_user_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
